<template>
  <s-tabs>
    <s-tab-item
      label="图片"
      icon="google-photos"
    />
    <s-tab-item
      label="音乐"
      icon="library-music"
    />
    <s-tab-item
      label="视频"
      icon="video"
    />
  </s-tabs>
</template>
