<template>
  <section>
    <s-tabs
      size="is-small"
      class="block"
    >
      <s-tab-item
        label="图片"
        icon="google-photos"
      />
      <s-tab-item
        label="音乐"
        icon="library-music"
      />
      <s-tab-item
        label="视频"
        icon="video"
      />
    </s-tabs>

    <s-tabs
      size="is-medium"
      class="block"
    >
      <s-tab-item
        label="图片"
        icon="google-photos"
      />
      <s-tab-item
        label="音乐"
        icon="library-music"
      />
      <s-tab-item
        label="视频"
        icon="video"
      />
    </s-tabs>

    <s-tabs
      size="is-large"
      class="block"
    >
      <s-tab-item
        label="图片"
        icon="google-photos"
      />
      <s-tab-item
        label="音乐"
        icon="library-music"
      />
      <s-tab-item
        label="视频"
        icon="video"
      />
    </s-tabs>
  </section>
</template>
